#!/usr/bin/bash

set -eu -o errexit -o noclobber -o nounset

PYVERSION=$(python3 -c "from platform import python_version_tuple as pvt; print(''.join(pvt()[:-1]))") # Gather python version
DOCDIR="$HOME/.local/share/docs/python3"                                                               # Set docdir

! getopt --test >/dev/null # Check for enhanced getopt

if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
	echo "Getopt fail" # If not enhanced
	exit 1
fi

LONGOPTS=version: # Set options
OPTIONS=v:

! PARSED="$(getopt --options="$OPTIONS" --longoptions="$LONGOPTS" --name "$0" -- "$@")"
if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
	exit 2
fi

eval set -- "$PARSED" # Fix quoting

case "$1" in
-v | --version)
	PYVERSION="$2"
	;;
*)
	echo "Auto-selecting $PYVERSION"
	;;
esac

if [[ -f "$DOCDIR/$PYVERSION/index.html" ]]; then
	xdg-open "$DOCDIR/$PYVERSION/index.html" 2>/dev/null
else
	echo "Inexistent"
fi
